yamlversion: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - doc_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  watchdog:
    build: 
      context: .
      dockerfile: agents/watchdog/Dockerfile
    volumes:
      - ./data:/data:ro
      - ./logs:/logs
    environment:
      - WATCH_PATHS=/data
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app
    depends_on:
      - redis
    networks:
      - doc_network
    restart: unless-stopped

  ocr_agent:
    build: 
      context: .
      dockerfile: agents/ocr/Dockerfile
    volumes:
      - ./data:/data:ro
      - ./indices:/indices
      - ./logs:/logs
    environment:
      - REDIS_URL=redis://redis:6379
      - TESSERACT_LANG=deu+eng
      - PYTHONPATH=/app
    depends_on:
      - redis
    networks:
      - doc_network
    restart: unless-stopped

  indexer:
    build: 
      context: .
      dockerfile: agents/indexer/Dockerfile
    volumes:
      - ./data:/data:ro
      - ./indices:/indices
      - ./logs:/logs
    environment:
      - REDIS_URL=redis://redis:6379
      - INDEX_FORMAT=markdown_json
      - PII_REMOVAL=strict
      - LANGUAGE=de
      - PYTHONPATH=/app
    depends_on:
      - redis
    networks:
      - doc_network
    restart: unless-stopped

networks:
  doc_network:
    driver: bridge

volumes:
  redis_data:
