name: Auto Fix Imports & References

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Apply automatic code fixes
        run: |
          find . -type f -name "*.py" ! -path "./venv/*" -exec sed -i \
            -e 's|from huggingface_hub import cached_download|from huggingface_hub import hf_hub_download as cached_download|g' \
            -e '/^references *=/ s/=.*/= list(set(references))/' \
            {} +

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push auto-fix branch
        id: create_branch
        run: |
          TIMESTAMP=$(date +%s)
          BRANCH="auto/fix-${TIMESTAMP}"
          echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT

          git checkout -b "$BRANCH"

          # Ignore changes to GitHub Actions workflow files
          git add -u ':!**/.github/workflows/**'

          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "skip_pr=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          git commit -m "fix: auto-fix references, imports, and redundant list()"
          git push origin "$BRANCH"

      - name: Create Pull Request
        if: steps.create_branch.outputs.skip_pr != 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "fix: auto-fix references, imports, and redundant list()"
          title: "Auto-fix: imports, references cleanup"
          body: |
            This PR was automatically created by a GitHub Action.
            - Updated deprecated imports
            - Cleaned up `references = ...` patterns
            - Skipped pushing changes to `.github/workflows/`
          branch: ${{ steps.create_branch.outputs.branch_name }}
          base: ${{ github.ref_name }}

