name: Auto Fix Lint & Imports

on:
  push:
    branches: [ main, develop ]

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Auto-fix common issues
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          BRANCH_NAME="auto/fix-linting-imports"

          git checkout -b "$BRANCH_NAME"

          # === 1. Fix 'references' undefined ===
          grep -rl 'return list(set(references))' . | while read file; do
            sed -i '/return list(set(references))/i\references = []  # TODO: replace with actual references' "$file"
          done

          # === 2. Remove lines starting with 'python#' ===
          grep -rl '^python#' . | while read file; do
            sed -i '/^python#/d' "$file"
          done

          # === 3. Fix deprecated huggingface_hub import ===
          grep -rl 'from huggingface_hub import cached_download' . | while read file; do
            sed -i 's/from huggingface_hub import cached_download/from huggingface_hub import hf_hub_download as cached_download/' "$file"
          done

          if git diff --quiet; then
            echo "No fixes needed"
            exit 0
          fi

          git add .
          git commit -m "fix: auto-fix references, imports, and invalid comments"
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: auto/fix-linting-imports
          title: "chore: auto-fix references, imports, and comments"
          body: |
            This PR was automatically created by GitHub Actions to fix common lint/import issues:
            - undefined `references`
            - remove `python#` comment lines
            - replace deprecated `cached_download` with `hf_hub_download`
          commit-message: "fix: auto-fix references, imports, and invalid comments"
          delete-branch: true
